### ISSUE TITLE
Freeze verions in overrides

### ISSUE THREAD

**Issue by guillaume-pansier** [ars2062/freeze-package-versions#1]
Hi,

For now, the tool only freezes versions in the dependencies and devDependencies. Is there any reason not to freeze the versions in the "overrides" section ?

**Comment by ars2062** [comment]
there was no reason not to freeze the overrides section. it just didn't cross my mind. I will work on it if I find some time. but for now, I'm open to Pull Requests

**Comment by guillaume-pansier** [comment]
Thanks for the answer ! I got a bit of time today to look at the issue again, and it seems to me that the fix is pretty simple. I opened a pull request with the few needed modifications.

There's no tests, but I tried locally with a package.json with an overrides section, and it worked as expected.
